version: '3'
services:
  cms:
    build: cms
    expose:
      - "8080"
    depends_on:
    - mongo
  mongo:
    image: mongo
    expose:
    - "27017"
    volumes:
    - data-volume:/data/db
  webcache:
    build: webcache
    ports:
      - "80:80"
volumes:
  data-volume:
